dist: jammy
sudo: required
services:
  - docker

before_install:
  - docker build -t sroy102024/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sroy102024/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-888577047880"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
